# render.yaml
# Blueprint pour l'infrastructure PrismeIA sur Render
services:
  # Service Backend (Symfony API)
  - type: web
    name: prismeia-backend-staging
    runtime: docker
    repo: https://github.com/onPV/PrismeIA
    region: frankfurt
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile.prod
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prismeia-db-staging
          property: connectionString # corrigé ici
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - fromGroup: prismeia-secrets

  # Service Frontend (Next.js)
  - type: web
    name: prismeia-frontend-staging
    runtime: node
    repo: https://github.com/onPV/PrismeIA
    region: frankfurt
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    plan: free # <--- CETTE LIGNE GARANTIT L'UTILISATION DU PLAN GRATUIT

# Groupe de variables d'environnement secrètes
envVarGroups:
  - name: prismeia-secrets
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: MAILER_DSN
        value: "smtp://47cd2f5026438c:242fcbf79f98ad@sandbox.smtp.mailtrap.io:2525" # À remplir via Render Dashboard
      - key: JWT_PASSPHRASE
        value: "LemotdepassePrismeia2025" # À remplir aussi via Render Dashboard
      - key: JWT_SECRET_KEY
        value: "" # Peut être une chaîne PEM base64
      - key: JWT_PUBLIC_KEY
        value: ""

# Service Base de Données (PostgreSQL)
databases:
  - name: prismeia-db-staging
    region: frankfurt
    plan: free
