# render.yaml
# Blueprint pour l'infrastructure PrismeIA sur Render
services:
  # Service Backend (Symfony API)
  - type: web
    name: prismeia-backend-staging
    runtime: docker
    repo: https://github.com/onPV/PrismeIA
    region: frankfurt
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile.prod
    plan: free
    healthCheck: # <-- AJOUTÉ : Indispensable pour que Render sache que le service est prêt
      path: /healthz
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prismeia-db-staging
          property: internalUrl # corrigé ici
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - fromGroup: prismeia-secrets

  # Service Frontend (Next.js)
  - type: web
    name: prismeia-frontend-staging
    runtime: node
    repo: https://github.com/onPV/PrismeIA
    region: frankfurt
    branch: main
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    plan: free # <--- CETTE LIGNE GARANTIT L'UTILISATION DU PLAN GRATUIT
    rewrites:
      - source: /api/:path*
        destination: https://prismeia-backend-staging.onrender.com/api/:path*

# Groupe de variables d'environnement secrètes
envVarGroups:
  - name: prismeia-secrets
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: MAILER_DSN
      - key: JWT_PASSPHRASE
      - key: JWT_SECRET_KEY
      - key: JWT_PUBLIC_KEY

# Service Base de Données (PostgreSQL)
databases:
  - name: prismeia-db-staging
    region: frankfurt
    plan: free
