# backend/Dockerfile.dev
FROM php:8.3-fpm-alpine

# Définir le répertoire de travail dans le conteneur
WORKDIR /var/www/html

# Installer les dépendances système nécessaires
# curl pour télécharger Composer, git pour les dépendances VCS
# php83-cli pour exécuter l'installeur Composer
RUN apk add --no-cache \
    postgresql-dev \
    git \
    curl \
    php83-cli \
    php83-ctype \
    php83-curl \
    php83-dom \
    php83-fileinfo \
    php83-iconv \
    php83-intl \
    php83-mbstring \
    php83-pdo \
    php83-pdo_pgsql \
    php83-pecl-apcu \
    php83-session \
    php83-xml \
    php83-zip \
    && rm -rf /var/cache/apk/* # Nettoie le cache après installation

# Installer Composer globalement
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copier les fichiers du projet Symfony
COPY . .

# Installer les dépendances Composer du projet
# On utilise --no-dev pour une image plus propre, même en dev Docker
RUN composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

# Exposer le port PHP-FPM
EXPOSE 9000

# Commande par défaut pour lancer PHP-FPM
CMD ["php-fpm"]