# backend/config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    secret_key: "%env(resolve:JWT_PRIVATE_KEY_PATH)%"
    public_key: "%env(resolve:JWT_PUBLIC_KEY_PATH)%"
    pass_phrase: "%env(JWT_PASSPHRASE)%" # C'est le mot de passe que tu as entré pour la clé privée
    token_ttl: 3600 # Durée de vie du token en secondes (ici 1 heure)
    # Autres configurations (token_extractors, etc.) peuvent être ajoutées plus tard
