# backend/config/packages/stof_doctrine_extensions.yaml
stof_doctrine_extensions:
    default_locale: fr
    orm:
        default:
            timestampable: true # Active Timestampable pour toutes les entités par défaut
